#!/usr/bin/env python3
"""One-off patch for concept/book HTML pages generated before three tools.py fixes:

1. The back-link, <title>, and (book pages only) subtitle line all showed the
   raw absolute filesystem path used as `domain_yaml` (e.g.
   "/home/.../public/domains/linalg_ch05/input/graph") instead of a clean
   domain title, because domain_id derivation didn't handle domain_yaml being
   an absolute path (only a bare "{id}_graph.yaml" filename).
2. Pages were missing the "spl-credit"/"Powered by" marker text the graph
   page's node-click detail panel (concept_graph.py's renderExplanation)
   requires to render the fetched concept page in an iframe -- without it,
   every click silently fell through to "Content not found — generate it
   first," even for pages that existed and loaded fine.
3. The back-link's relative "../../" href doesn't resolve correctly on static
   hosting (404) -- removed entirely rather than fixed, since the graph
   page's own left sidebar (and the book index's own TOC nav) already cover
   navigation back to the domain.

All three are fixed in tools.py for anything generated from now on. This
script patches already-generated HTML in place so existing pages don't need
to be regenerated (each regeneration costs LLM calls/tokens for the payoff
section, which is never cache-covered).

Usage:
    python scripts/patch_generated_pages.py            # patch for real
    python scripts/patch_generated_pages.py --dry-run   # show what would change
"""
import argparse
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOMAINS_DIR = REPO_ROOT / "public" / "domains"

# Concept pages wrap the back-link in its own <header>; strip the whole block.
_HEADER_BLOCK_RE = re.compile(
    r'\s*<header>\s*<a href="[^"]*" class="back">[^<]*</a>\s*</header>'
)
# Book index pages have the back-link as a bare line inside <nav class="toc">,
# alongside the "Contents" heading and TOC list -- remove just the link line.
_BACK_LINK_LINE_RE = re.compile(r'[ \t]*<a href="[^"]*" class="back">[^<]*</a>\n')
_FOOTER = '<footer class="spl-credit">Generated by SPL &middot; Powered by SPL.py</footer>'

# <title>...| BROKEN</title> (concept pages) or <title>...— BROKEN</title>
# (book index pages) -- the broken domain_title trails the last " | " or
# " — " separator in both templates.
_TITLE_RE = re.compile(r'<title>(.*)</title>')
_SUBTITLE_RE = re.compile(r'(<p class="subtitle">)[^<]*( &middot; Generated by SPL</p>)')

_BROKEN_MARKER = re.compile(r'/home/', re.IGNORECASE)


def _domain_id_from_path(html_path: Path) -> str | None:
    """.../public/domains/{domain_id}/output/... -> domain_id."""
    try:
        rel = html_path.relative_to(DOMAINS_DIR)
    except ValueError:
        return None
    parts = rel.parts
    return parts[0] if parts else None


def _fix_title(text: str, correct_title: str) -> str:
    def repl(m: re.Match) -> str:
        title = m.group(1)
        if not _BROKEN_MARKER.search(title):
            return m.group(0)
        for sep in (' | ', ' — '):
            if sep in title:
                prefix = title.rsplit(sep, 1)[0]
                return f'<title>{prefix}{sep}{correct_title}</title>'
        return f'<title>{correct_title}</title>'
    return _TITLE_RE.sub(repl, text, count=1)


def patch_file(path: Path, dry_run: bool) -> bool:
    domain_id = _domain_id_from_path(path)
    text = path.read_text(encoding="utf-8")
    original = text

    text = _HEADER_BLOCK_RE.sub('', text)
    text = _BACK_LINK_LINE_RE.sub('', text)

    if domain_id:
        correct_title = domain_id.replace('_', ' ').title()
        text = _fix_title(text, correct_title)
        text = _SUBTITLE_RE.sub(lambda m: f'{m.group(1)}{correct_title}{m.group(2)}', text)

    if "spl-credit" not in text and "</main>" in text:
        text = text.replace("</main>", f"{_FOOTER}\n  </main>", 1)

    if text == original:
        return False

    if not dry_run:
        path.write_text(text, encoding="utf-8")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    paths = sorted(DOMAINS_DIR.glob("*/output/**/concept_*.html")) + \
            sorted(DOMAINS_DIR.glob("*/output/**/book_*.html"))

    changed = 0
    for p in paths:
        if patch_file(p, args.dry_run):
            changed += 1
            print(f"  {'(dry run) would patch' if args.dry_run else 'patched'}: {p.relative_to(REPO_ROOT)}")

    print(f"\n{changed} of {len(paths)} pages {'need patching' if args.dry_run else 'patched'}.")


if __name__ == "__main__":
    main()
